CREATE TABLE TARGETS (
	id INTEGER PRIMARY KEY AUTOINCREMENT,
	TARGET TEXT, -- UNIQUE
	REPLACED_WITH TEXT,
	SKINNER TEXT NOT NULL,
	STATUS BOOLEAN,
	LAST_USE_DATE TIMESTAMP DEFAULT NULL,
	LAST_USE_CMD TEXT DEFAULT NULL,
	CREATED_AT TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);